name: Brian Cauley
favicon: null
layout_spectrum: 0.18980446318164468
typography_spectrum: 0.48810316366143525
title: Brian Cauley
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.07031806651502848
  lightness: 0.956416935659945
  saturation: 0.4198484313674271
  rhythmicContrast: 0.10496759647503495
purpose: []
